// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace MLExampleML.Model
{
    public class ModelInput
    {
        [ColumnName("Code"), LoadColumn(0)]
        public string Code { get; set; }


        [ColumnName("English"), LoadColumn(1)]
        public string English { get; set; }


    }
}
